apiVersion: v1
kind: Config

clusters:
- cluster:
    certificate-authority: /root/ca.crt
    server: https://192.168.99.103:8443
  name: lwcluster

contexts:
- context:
    cluster: lwcluster
    user: shivam

users:
- name: shivam
  user:
    client-certificate: /root/client.crt
    client-key: /root/client.key
